[package]
name = "imag-ref"
version = "0.4.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-ref command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
semver = "0.5.1"
clap = ">=2.17"
log = "0.3"
version = "2.0.1"

[dependencies.libimagstore]
path = "../../../lib/core/libimagstore"

[dependencies.libimagrt]
path = "../../../lib/core/libimagrt"

[dependencies.libimagerror]
path = "../../../lib/core/libimagerror"

[dependencies.libimagentryref]
path = "../../../lib/entry/libimagentryref"

[dependencies.libimagentrylist]
path = "../../../lib/entry/libimagentrylist"

[dependencies.libimaginteraction]
path = "../../../lib/etc/libimaginteraction"

[dependencies.libimagutil]
path = "../../../lib/etc/libimagutil"

