[package]
name = "libimagstorestdhook"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Library for the imag core distribution"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
toml = "0.2.*"
log = "0.3"
fs2 = "0.3"
git2 = "0.5"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagentrylink]
path = "../libimagentrylink"

[dependencies.libimaginteraction]
path = "../libimaginteraction"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimagutil]
path = "../libimagutil"

