[package]
name = "imag-documentation"
version = "0.2.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Documentation crate of the imag distribution. Does not contain functionality"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]

[dependencies.libimagentryfilter]
path = "../libimagentryfilter"

[dependencies.libimagentrylink]
path = "../libimagentrylink"

[dependencies.libimagentrylist]
path = "../libimagentrylist"

[dependencies.libimagentrymarkdown]
path = "../libimagentrymarkdown"

[dependencies.libimagentrytag]
path = "../libimagentrytag"

[dependencies.libimagentryview]
path = "../libimagentryview"

[dependencies.libimagerror]
path = "../libimagerror"

[dependencies.libimaginteraction]
path = "../libimaginteraction"

[dependencies.libimagnotes]
path = "../libimagnotes"

[dependencies.libimagref]
path = "../libimagref"

[dependencies.libimagrt]
path = "../libimagrt"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagstorestdhook]
path = "../libimagstorestdhook"

[dependencies.libimagtimeui]
path = "../libimagtimeui"

[dependencies.libimagutil]
path = "../libimagutil"

