[package]
name = "imag-diary"
version = "0.4.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]

description = "Part of the imag core distribution: imag-diary command"

keywords    = ["imag", "PIM", "personal", "information", "management"]
readme      = "../README.md"
license     = "LGPL-2.1"

documentation = "https://matthiasbeyer.github.io/imag/imag_documentation/index.html"
repository    = "https://github.com/matthiasbeyer/imag"
homepage      = "http://imag-pim.org"

[dependencies]
chrono = "0.4"
version = "2.0"
clap = "2.*"
log = "0.3"

[dependencies.libimagerror]
path = "../../../lib/core/libimagerror"

[dependencies.libimagstore]
path = "../../../lib/core/libimagstore"

[dependencies.libimagrt]
path = "../../../lib/core/libimagrt"

[dependencies.libimagdiary]
path = "../../../lib/domain/libimagdiary"

[dependencies.libimagentryedit]
path = "../../../lib/entry/libimagentryedit"

[dependencies.libimagentrylist]
path = "../../../lib/entry/libimagentrylist"

[dependencies.libimaginteraction]
path = "../../../lib/etc/libimaginteraction"

[dependencies.libimagutil]
path = "../../../lib/etc/libimagutil"

[dependencies.libimagtimeui]
path = "../../../lib/etc/libimagtimeui"

